### ISSUE TITLE
Texture/incompatibility issue

### ISSUE THREAD

**Issue by iPhockU** [Mechalopa/Hostile-Mobs-and-Girls#17]
Hello, I am using the Improved Mobs mod on my server, which equips all mobs with all available armor and weapons, apparently there is a problem with the texture of the Necrotic Chainmail armor and the Mummy mob from the Rotten Creatures mod .

[crash-2023-05-29_17.45.18-client.txt](https://github.com/Mechalopa/Hostile-Mobs-and-Girls/files/11594578/crash-2023-05-29_17.45.18-client.txt)

![image_2023-05-29_175908835](https://github.com/Mechalopa/Hostile-Mobs-and-Girls/assets/134979780/489699a4-9d2c-4271-a774-75ae54e7e1b6)

**Comment by Mechalopa** [comment]
I have checked and this seems to be a known issue with Rotten Creatures.
It seems that this will be fixed in the next Rotten Creatures update.
Reference: https://github.com/teamfusion/rottencreatures/issues/23
