### ISSUE TITLE
[1.18.2] Subtltles on mobs aren't properly formatted

### ISSUE THREAD

**Issue by Reshy** [Mechalopa/Hostile-Mobs-and-Girls#19]
![2023-06-25_08 02 12](https://github.com/Mechalopa/Hostile-Mobs-and-Girls/assets/2096384/de1a8804-e920-476c-ac5a-b79dca2ee4e4)
![2023-06-25_08 05 02](https://github.com/Mechalopa/Hostile-Mobs-and-Girls/assets/2096384/0a462d49-300e-4a64-93e1-c6983dc10732)

(Also spider nests can't climb like a spider.

**Comment by Mechalopa** [comment]
In the latest version, translations of subtitles have been added. (en_us only)
However, there are still many inconsistencies in the subtitles where vanilla sounds are used...

As for spider's nest, it works as intended.
