### ISSUE TITLE
Water Aspect enchantment duplicating

### ISSUE THREAD

**Issue by SodiumZH** [Mechalopa/Hostile-Mobs-and-Girls#21]
Water Aspect enchantment rarely appears twice on a single weapon both on the enchantment table and in treasure chests. If such weapon is operated on the Anvil the duplicating enchantment will disappear. I didn't test if the effect will be really doubled.
Version 1.19.2 - 6.2.0
The image below showed a sword with duplicated Water Aspect IV enchantment from a treasure chest. I;ve also met a case in which one sword was enchanted with two Water Aspect V effects on the Enchantment Table. In the latter case the shown enchantment was Water Aspect. I've never encountered any duplication cases on the Enchantment Table that the shown enchantment wasn't Water Aspect. ("水之所向" = Water Aspect) 

![2023-07-21_18 28 31](https://github.com/Mechalopa/Hostile-Mobs-and-Girls/assets/46860829/df4429b9-0e67-4f82-a424-a4b64a9c4940)

**Comment by Mechalopa** [comment]
Already fixed in version 6.2.1.
