### ISSUE TITLE
{Compatibility} (hmag-forge-mc1.19.2-6.2.7) and (The Aether - 1.19.2-1.0.0-beta.1.2-forge)

### ISSUE THREAD

**Issue by togera13** [Mechalopa/Hostile-Mobs-and-Girls#24]
https://www.curseforge.com/minecraft/mc-mods/hostile-mobs-and-girls/files/4787085
https://www.curseforge.com/minecraft/mc-mods/aether/files/4771515

Upon hosting multiplayer anyone who attempts to join the host or the server will get disconnected & will not be able to join as long as these two mods are present.

This is very disappointing as I like both mods a lot.

**Comment by togera13** [comment]
![Screenshot 2023-10-18 023538](https://github.com/Mechalopa/Hostile-Mobs-and-Girls/assets/119283778/5177af64-e7ea-436c-9467-a466400dd1be)
Forge version is 43.3.2. Again, with only The Aether & HMAG running on the server.

**Comment by Mechalopa** [comment]
Apparently, if the json file that adds the aether repairing recipe is deleted, it will join to the server successfully.
https://github.com/Mechalopa/Hostile-Mobs-and-Girls/tree/1.19.2/src/main/resources/data/hmag/recipes/aether
If the problem persists for a long time, I would delete the file.

**Comment by bconlon1** [comment]
I believe this is being caused by a lack of category field in these recipe jsons, like here: https://github.com/The-Aether-Team/The-Aether/blob/1.19.2-develop/src/generated/resources/data/aether/recipes/zanite_sword_repairing.json.

**Comment by Mechalopa** [comment]
I had overlooked that only 1.19.2 requires it. I will fix this in the next update. Thanks :)
