### ISSUE TITLE
Does this mod conflict with gia mod

### ISSUE THREAD

**Issue by lSherozl** [Mechalopa/Hostile-Mobs-and-Girls#28]
The gia mod was also updated to 1.19.2, I want to see about adding both of these mods, is it possible or not since they have similar creatures with same names

**Comment by Mechalopa** [comment]
Does "gia mod" mean Grimoire of Gaia? No conflicts.

**Comment by lSherozl** [comment]
> Does "gia mod" mean Grimoire of Gaia? No conflicts.

Yes it does, thank u for answering the question
