### ISSUE TITLE
incompatability with Cold Sweat mod

### ISSUE THREAD

**Issue by kunrian** [Mechalopa/Hostile-Mobs-and-Girls#31]
Hello, 
It appears that there is an issue with some sort of adding a leather modifier
https://www.curseforge.com/minecraft/mc-mods/cold-sweat

It doesn't like something upon server joining, or single player world loading. 
Pastebin to direct join event: https://pastebin.com/K8kknvCW

Attached debug log contains all server loading information, but majority of it(around 120k lines) is enigmatic legacy's loot table debugging

I have let the author of coldsweat know as well

[debug(1).log](https://github.com/Mechalopa/Hostile-Mobs-and-Girls/files/14547455/debug.1.log)

**Comment by Mechalopa** [comment]
Ummm, perhaps there is a problem with Cold Sweat mod.

https://github.com/bonsaistudi0s/Creatures_And_Beasts-Forge/issues/68
The same problem seems to happen with Creatures and Beasts.
