### ISSUE TITLE
1.12.2 lost version?

### ISSUE THREAD

**Issue by jarezzz** [Mechalopa/Hostile-Mobs-and-Girls#33]
Why is there no 1.12.2 version of this mod? This is the latest version I have
[HMaG-mc1.12.2-3.2.0.zip](https://github.com/user-attachments/files/15539186/HMaG-mc1.12.2-3.2.0.zip)

**Comment by SodiumZH** [comment]
1.12.2 and below versions seem to have been removed by the author and out of support.
