### ISSUE TITLE
Feature Request 1.18.2:

### ISSUE THREAD

**Issue by Tyrius1** [Mechalopa/Hostile-Mobs-and-Girls#4]
Could you add a per mob biome whitelist? 
I'd like to specify the biomes in which some of these amazingly mythical mobs spawn in to be in more magical modded biomes.
I see the biome blacklist but that's a bit too vague to specify proper habitats.
I would like to whitelist ghosts for instance to minecraft:dark_forest, biomesoplenty:ominous_woods and graveyard:haunted_forest for example. 
A tag to be changed via datapack would also work.

Mob suggestion:
Succubi (With Lilith Boss Variant?)
Gorgons (With Medusa Boss Variant?)
Dryads (Peaceful unless you chop down a tree next to them.)
Arachne
Mounted Dullahan

**Comment by Tyrius1** [comment]
モブごとのバイオームホワイトリストを追加できますか？
これらの驚くほど神話的なMobのいくつかが、より魔法の改造されたバイオームに出現するバイオームを指定したいと思います。
バイオームブラックリストは表示されますが、適切な生息地を指定するには少し曖昧すぎます。
たとえば、ゴーストをminecraft：dark_forest、biomesoplenty：ominous_woods、graveyard：haunted_forestなどにホワイトリストに登録したいと思います。
データパックを介して変更されるタグも機能します。

暴徒の提案：
サキュバス（リリスボスバリアント付き？）
ゴルゴン（メデューサボスバリアント付き？）
ドリュアス（隣の木を切り倒さない限り平和です。）
アラクネ
マウントされたデュラハン

お役に立てれば ：）

**Comment by Mechalopa** [comment]
Umm, I think the detailed biome specific mob spawns will be realized by biome tags after the update to 1.19.
No plans as of 1.18.2. Sorry.

**Comment by Tyrius1** [comment]
Awesome looking forward to it! :)
