### ISSUE TITLE
1.19.2 Tamable blue

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Mechalopa/Hostile-Mobs-and-Girls#5]
So I really like some are passive could we tame them with for example a golden apple?

**Comment by Mechalopa** [comment]
Sorry, I have no plans to do so.

**Comment by SodiumZH** [comment]
> So I really like some are passive could we tame them with for example a golden apple?

I'm planning to make an additive module to HMaG and add features of taming. Would you be interested in this?

**Comment by P3rf3ctXZer0** [comment]
Yes please!
