### ISSUE TITLE
Licence of Adjustment Mods of HMaG

### ISSUE THREAD

**Issue by SodiumZH** [Mechalopa/Hostile-Mobs-and-Girls#6]
Dear Mr. Mechalopa,

I'd like to inquire if HMaG allows development of additional expanding mods.
Currently I'm planning to develop an expanding mod of HMaG (not a modpack), adding some additional features. It will mandatorily depend on HMaG. My planned features are some new recipes, blocks and mob taming(#5). Is it licenced to do so?

Sincerely,
SodiumZH

**Comment by Mechalopa** [comment]
Yes, you are free to produce them as long as you strictly adhere to the license.

**Comment by SodiumZH** [comment]
> Yes, you are free to produce them as long as you strictly adhere to the license.

Great! Thank you very much, and your mod is really admirable.
