### ISSUE TITLE
You asked me a question but never gave a chance to answer! Yes I would be interested in a taming mechanic!

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Mechalopa/Hostile-Mobs-and-Girls#8]
Yes please anything tamable please. Also Add male variants and breeding would be nice too - anything you add would be nice and promise to report issues also in the future when something is resolved I will close it myself promise so wait for me to close issues ;)

**Comment by SodiumZH** [comment]
As the plan is just beginning I haven't published my repo yet. Would you be able to provide an e-mail address? I'll make an elementary document of my plan and send it to you.

**Comment by P3rf3ctXZer0** [comment]
Hm I would rather you just make a project page and add me to it. I don't use email for anything but verification and I am always able to see my github. All you need to to is this @SodiumZH but of course my user name.

**Comment by SodiumZH** [comment]
> Hm I would rather you just make a project page and add me to it. I don't use email for anything but verification and I am always able to see my github. All you need to to is this @SodiumZH but of course my user name.

I've invited you to my repo. Also, would you be able to provide a contact information besides Github? (Github doesn't support personal communication and I don't think it's a good idea to chat in repos' issues.)
